version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
    - .:/go/src/app
    depends_on:
    - db
    - mail
    ports:
    command: app
    # command: /bin/sh
    # tty: true
    - 80:80

  db:
    image: postgres
    environment:
    - POSTGRES_USER=${DATABASE_USER}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    - POSTGRES_DB=${DATABASE_NAME}
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./postgresql.conf:/etc/postgresql/postgresql.conf
    - ./.postgres:/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  mail:
    image: mailhog/mailhog
    ports:
    - 8025:8025
